header <- dashboardHeader(title = 'Methane Emissions',
                          userOutput("me"))

sideBar <- dashboardSidebar(sidebarMenu(menuItem('Description',
                                                 tabName = 'info',
                                                 icon = icon('info')),
                                        menuItem('Charts',
                                                 tabName = 'charts',
                                                 icon = icon('chart-line'),
                                                 menuSubItem('Overall',
                                                             tabName = 'overall',
                                                             icon = icon('calculator')),
                                                 menuSubItem('By sector & Country',
                                                             tabName = 'especific',
                                                             icon = icon('chart-line'))),
                                        menuItem('Table',
                                                 tabName = 'table',
                                                 icon = icon('table'))))


body <- dashboardBody(tabItems(tabItem(tabName = 'info',
                                       column(width = 4,
                                              h1('Context', style = 'font-family: Verdana', align = 'center'),
                                              htmlOutput('description', style = 'font-family: Verdana')),
                                       column(width = 4,
                                              h1('Metadata', style = 'font-family: Verdana', align = 'center'),
                                              htmlOutput('metadata', style = 'font-family: Verdana')),
                                       column(width = 4,
                                              h1('Summary', style = 'font-family: Verdana', align = 'center'),
                                              htmlOutput('summary', style = 'font-family: Verdana'))),
                               tabItem(tabName = 'especific',
                                       fluidPage(box(width = 12,
                                                     title = "Highest values reached",
                                                     status = "danger",
                                                     solidHeader = TRUE,
                                                     collapsible = TRUE,
                                                     valueBoxOutput('Agriculture'),
                                                     valueBoxOutput('LandUseChangeForestry'),
                                                     valueBoxOutput('Waste'),
                                                     valueBoxOutput('Energy'),
                                                     valueBoxOutput('OtherFuelCombustion'),
                                                     valueBoxOutput('FugitiveEmissions'),
                                                     valueBoxOutput('TotalexcludingLUCF'),
                                                     valueBoxOutput('IndustrialProcesses'),
                                                     valueBoxOutput('TotalincludingLUCF'))),
                                       column(width = 4,
                                              offset = 4,
                                              selectInput('country',
                                                          label = 'Country',
                                                          choices = unique(country),
                                                          selected = 'Argentina',
                                                          width = "100%")),
                                       fluidRow(box(width = 12,
                                                    title = "Methane Emission by all sectors over the years",
                                                    status = "danger",
                                                    solidHeader = TRUE,
                                                    collapsible = TRUE,
                                                    highchartOutput('linePlot'))),
                                       fluidRow(column(width = 4,
                                                       offset = 2,
                                                       selectInput('country2',
                                                                   label = 'Country',
                                                                   choices = unique(country),
                                                                   selected = 'Argentina',
                                                                   width = "100%")),
                                                column(width = 4,
                                                       selectInput('sector',
                                                                   label = 'Sector',
                                                                   choices = unique(sector),
                                                                   selected = 'Agriculture',
                                                                   width = "100%"))),
                                       fluidRow(box(width = 12,
                                                    title = "Methane Emission by sector over the years",
                                                    status = "danger",
                                                    solidHeader = TRUE,
                                                    collapsible = TRUE,
                                                    highchartOutput('linePlotSector')))),
                               tabItem(tabName = 'overall',
                                       column(width = 4,
                                              offset = 4,
                                              selectInput('sectorOverall',
                                                          label = 'Sector',
                                                          choices = unique(sector),
                                                          selected = 'Argentina',
                                                          width = "100%")),
                                       fluidRow(box(width = 12,
                                                    title = "Methane Emission by sector over the years",
                                                    status = "danger",
                                                    solidHeader = TRUE,
                                                    collapsible = TRUE,
                                                    highchartOutput('overall'))),
                                       fluidRow(box(width = 12,
                                                    title = "Methane Emission by sector over the years",
                                                    status = "danger",
                                                    solidHeader = TRUE,
                                                    collapsible = TRUE,
                                                    highchartOutput('methaneEmissionsoverall'),
                                                    highchartOutput('overallPie')))),
                               tabItem(tabName = 'table',
                                       fluidRow(column(width = 12,
                                                       dataTableOutput('table'))))),
                      shinyDashboardThemes(theme = 'flat_red'),
                      tags$head(tags$style(HTML('.skin-blue .main-header li.user-header {
                                                background-color: #CF395C;}'))))

ui <- dashboardPage(header,
                    sideBar,
                    body)
